from Bio import SeqIO
from Bio import codonalign
from Bio import AlignIO
from Bio.Alphabet import generic_dna
from Bio.Alphabet import generic_protein
import os

wd = os.getcwd()

FAM, = glob_wildcards("families/family_{fam}.fna")

rule final:
    input:
        expand("families/family_{fam}.aln.codon.FUBAR.json", fam= FAM)

rule clean_fna:
    input:
        "families/family_{fam}.fna"
    output:
        "families/family_{fam}.fna.cleaned"
    run:
        new_sequences = []
        for record in SeqIO.parse(input[0], "fasta"):
            if len(record.seq) % 3 != 0:
                record.seq = record.seq + "N"
                new_sequences.append(record)
            else:
                new_sequences.append(record)
        SeqIO.write(new_sequences, output[0], "fasta")

rule mafft:
    input:
        "families/family_{fam}.faa"
    output:
        "families/family_{fam}.aln"
    shell:
        "mafft --auto --thread 1 {input} > {output}"
rule fasttree:
    input:
        "families/family_{fam}.aln"
    output:
        "families/family_{fam}.tree"
    conda:
        "envs/fasttree.yaml"
    shell:
        "fasttree -nosupport {input} > {output} || true"
rule codonaln:
    input:
        pro_align = "families/family_{fam}.aln",
        nucl_seqs = "families/family_{fam}.fna.cleaned"
    output:
        alignment = "families/family_{fam}.aln.codon"
    run:
        aa_aln = AlignIO.read(input.pro_align, "fasta", alphabet=generic_protein)
        na_seq = SeqIO.to_dict(SeqIO.parse(input.nucl_seqs, "fasta", alphabet=generic_dna))

        codonalign.default_codon_table.forward_table["NTT"] = "X"
        codonalign.default_codon_table.forward_table["NNN"] = "X"  # quick fix for Ns in the dataset
        codonalign.default_codon_table.forward_table["GNN"] = "X"
        codonalign.default_codon_table.forward_table["RTT"] = "X"
        codonalign.default_codon_table.forward_table["GGN"] = "G"
        codonalign.default_codon_table.forward_table["GGY"] = "G"
        codonalign.default_codon_table.forward_table["GGK"] = "G"
        codonalign.default_codon_table.forward_table["GGR"] = "G"
        codonalign.default_codon_table.forward_table["CCS"] = "P"
        codonalign.default_codon_table.forward_table["CCN"] = "P"
        codonalign.default_codon_table.forward_table["CCY"] = "P"
        codonalign.default_codon_table.forward_table["CCK"] = "P"
        codonalign.default_codon_table.forward_table["CCM"] = "P"
        codonalign.default_codon_table.forward_table["CTN"] = "L"
        codonalign.default_codon_table.forward_table["CTR"] = "L"
        codonalign.default_codon_table.forward_table["CTK"] = "L"
        codonalign.default_codon_table.forward_table["CWC"] = "X"
        codonalign.default_codon_table.forward_table["CWS"] = "X"
        codonalign.default_codon_table.forward_table["WAC"] = "X"
        codonalign.default_codon_table.forward_table["CAN"] = "X"
        codonalign.default_codon_table.forward_table["TRS"] = "X"
        codonalign.default_codon_table.forward_table["TRK"] = "X"
        codonalign.default_codon_table.forward_table["RCA"] = "X"
        codonalign.default_codon_table.forward_table["CAM"] = "X"
        codonalign.default_codon_table.forward_table["MGR"] = "X"
        codonalign.default_codon_table.forward_table["MRC"] = "X"
        codonalign.default_codon_table.forward_table["NCC"] = "X"
        codonalign.default_codon_table.forward_table["NNC"] = "X"
        codonalign.default_codon_table.forward_table["NNA"] = "X"
        codonalign.default_codon_table.forward_table["ANN"] = "X"
        codonalign.default_codon_table.forward_table["CNN"] = "X"
        codonalign.default_codon_table.forward_table["CKC"] = "X"
        codonalign.default_codon_table.forward_table["NNG"] = "X"
        codonalign.default_codon_table.forward_table["AAN"] = "X"
        codonalign.default_codon_table.forward_table["NAA"] = "X"
        codonalign.default_codon_table.forward_table["NAT"] = "X"
        codonalign.default_codon_table.forward_table["TTN"] = "X"
        codonalign.default_codon_table.forward_table["NTC"] = "X"
        codonalign.default_codon_table.forward_table["NTA"] = "X"
        codonalign.default_codon_table.forward_table["NTG"] = "X"
        codonalign.default_codon_table.forward_table["NGC"] = "X"
        codonalign.default_codon_table.forward_table["NGA"] = "X"
        codonalign.default_codon_table.forward_table["NGT"] = "X"
        codonalign.default_codon_table.forward_table["ATN"] = "X"
        codonalign.default_codon_table.forward_table["ATY"] = "I"
        codonalign.default_codon_table.forward_table["AAS"] = "X"
        codonalign.default_codon_table.forward_table["ASC"] = "X"
        codonalign.default_codon_table.forward_table["ATS"] = "X"
        codonalign.default_codon_table.forward_table["TAN"] = "X"
        codonalign.default_codon_table.forward_table["TAY"] = "Y"
        codonalign.default_codon_table.forward_table["GAN"] = "X"
        codonalign.default_codon_table.forward_table["AYC"] = "X"
        codonalign.default_codon_table.forward_table["CNC"] = "X"
        codonalign.default_codon_table.forward_table["NCG"] = "X"
        codonalign.default_codon_table.forward_table["NGG"] = "X"
        codonalign.default_codon_table.forward_table["NNT"] = "X"
        codonalign.default_codon_table.forward_table["CYC"] = "X"
        codonalign.default_codon_table.forward_table["NAG"] = "X"
        codonalign.default_codon_table.forward_table["ACN"] = "T"
        codonalign.default_codon_table.forward_table["ACK"] = "T"
        codonalign.default_codon_table.forward_table["ACR"] = "T"
        codonalign.default_codon_table.forward_table["ACY"] = "T"
        codonalign.default_codon_table.forward_table["ACS"] = "T"
        codonalign.default_codon_table.forward_table["KCG"] = "X"
        codonalign.default_codon_table.forward_table["RCT"] = "X"
        codonalign.default_codon_table.forward_table["RCC"] = "X"
        codonalign.default_codon_table.forward_table["RCG"] = "X"
        codonalign.default_codon_table.forward_table["RGC"] = "X"
        codonalign.default_codon_table.forward_table["NAC"] = "X"
        codonalign.default_codon_table.forward_table["TCN"] = "S"
        codonalign.default_codon_table.forward_table["TCR"] = "S"
        codonalign.default_codon_table.forward_table["TCK"] = "S"
        codonalign.default_codon_table.forward_table["TCM"] = "S"
        codonalign.default_codon_table.forward_table["TCS"] = "S"
        codonalign.default_codon_table.forward_table["TCY"] = "S"
        codonalign.default_codon_table.forward_table["AGN"] = "X"
        codonalign.default_codon_table.forward_table["SGG"] = "X"
        codonalign.default_codon_table.forward_table["KAT"] = "X"
        codonalign.default_codon_table.forward_table["KAC"] = "X"
        codonalign.default_codon_table.forward_table["CGN"] = "R"
        codonalign.default_codon_table.forward_table["CGR"] = "R"
        codonalign.default_codon_table.forward_table["TGN"] = "X"
        codonalign.default_codon_table.forward_table["TNN"] = "X"
        codonalign.default_codon_table.forward_table["GCN"] = "A"
        codonalign.default_codon_table.forward_table["GCY"] = "A"
        codonalign.default_codon_table.forward_table["NCT"] = "X"
        codonalign.default_codon_table.forward_table["NCN"] = "X"
        codonalign.default_codon_table.forward_table["GTN"] = "V"
        codonalign.default_codon_table.forward_table["GTY"] = "V"
        codonalign.default_codon_table.forward_table["GTK"] = "V"
        codonalign.default_codon_table.forward_table["GTM"] = "V"
        codonalign.default_codon_table.forward_table["GRT"] = "X"
        codonalign.default_codon_table.forward_table["TMC"] = "X"
        codonalign.default_codon_table.forward_table["TKG"] = "X"
        codonalign.default_codon_table.forward_table["TKM"] = "X"
        codonalign.default_codon_table.forward_table["NCA"] = "X"
        codonalign.default_codon_table.forward_table["GNG"] = "X"
        codonalign.default_codon_table.forward_table["WGC"] = "X"
        codonalign.default_codon_table.forward_table["GNC"] = "X"
        codonalign.default_codon_table.forward_table["ANA"] = "X"
        codonalign.default_codon_table.forward_table["GNT"] = "X"
        codonalign.default_codon_table.forward_table["ANT"] = "X"
        codonalign.default_codon_table.forward_table["RAC"] = "B"
        codonalign.default_codon_table.forward_table["RAA"] = "X"
        codonalign.default_codon_table.forward_table["NGN"] = "X"
        codonalign.default_codon_table.forward_table["KGG"] = "X"
        codonalign.default_codon_table.forward_table["RWY"] = "X"
        codonalign.default_codon_table.forward_table["GNA"] = "X"
        codonalign.default_codon_table.forward_table["CNG"] = "X"
        codonalign.default_codon_table.forward_table["CNA"] = "X"
        codonalign.default_codon_table.forward_table["ANG"] = "X"
        codonalign.default_codon_table.forward_table["CNT"] = "X"
        codonalign.default_codon_table.forward_table["TNC"] = "X"
        codonalign.default_codon_table.forward_table["TTK"] = "X"
        codonalign.default_codon_table.forward_table["ANC"] = "X"
        codonalign.default_codon_table.forward_table["TNA"] = "X"
        codonalign.default_codon_table.forward_table["TNT"] = "X"
        codonalign.default_codon_table.forward_table["MCC"] = "X"
        codonalign.default_codon_table.forward_table["TNG"] = "X"
        codonalign.default_codon_table.forward_table["NTN"] = "X"
        codonalign.default_codon_table.forward_table["YGT"] = "X"
        codonalign.default_codon_table.forward_table["NAN"] = "X"
        codonalign.default_codon_table.forward_table["GAM"] = "X"
        codonalign.default_codon_table.forward_table["GAY"] = "D"
        codonalign.default_codon_table.forward_table["GAR"] = "E"
        codonalign.default_codon_table.forward_table["AMC"] = "X"
        codonalign.default_codon_table.forward_table["YTC"] = "X"
        codonalign.default_codon_table.forward_table["YTG"] = "L"
        codonalign.default_codon_table.forward_table["YTA"] = "L"
        codonalign.default_codon_table.forward_table["YAC"] = "X"
        codonalign.default_codon_table.forward_table["WCG"] = "X"
        codonalign.default_codon_table.forward_table["GMA"] = "X"
        codonalign.default_codon_table.forward_table["GMC"] = "X"
        codonalign.default_codon_table.forward_table["ACM"] = "T"
        codonalign.default_codon_table.forward_table["ACW"] = "T"
        codonalign.default_codon_table.forward_table["CGY"] = "R"
        codonalign.default_codon_table.forward_table["GYC"] = "X"
        codonalign.default_codon_table.forward_table["GYT"] = "X"
        codonalign.default_codon_table.forward_table["WCC"] = "X"
        codonalign.default_codon_table.forward_table["CSC"] = "X"
        codonalign.default_codon_table.forward_table["SCT"] = "X"
        codonalign.default_codon_table.forward_table["SCC"] = "X"
        codonalign.default_codon_table.forward_table["CRT"] = "X"
        codonalign.default_codon_table.forward_table["CRC"] = "X"
        codonalign.default_codon_table.forward_table["YCC"] = "X"
        codonalign.default_codon_table.forward_table["GAK"] = "X"
        codonalign.default_codon_table.forward_table["AKC"] = "X"
        codonalign.default_codon_table.forward_table["AWC"] = "X"
        codonalign.default_codon_table.forward_table["AYA"] = "X"
        codonalign.default_codon_table.forward_table["AYG"] = "X"
        codonalign.default_codon_table.forward_table["CAY"] = "H"
        codonalign.default_codon_table.forward_table["CAR"] = "Q"
        codonalign.default_codon_table.forward_table["AAR"] = "K"
        codonalign.default_codon_table.forward_table["GCR"] = "A"
        codonalign.default_codon_table.forward_table["CGS"] = "R"
        codonalign.default_codon_table.forward_table["AAW"] = "X"
        codonalign.default_codon_table.forward_table["RAT"] = "B"
        codonalign.default_codon_table.forward_table["GGM"] = "G"
        codonalign.default_codon_table.forward_table["GGS"] = "G"
        codonalign.default_codon_table.forward_table["CTM"] = "L"
        codonalign.default_codon_table.forward_table["CTW"] = "L"
        codonalign.default_codon_table.forward_table["MGG"] = "R"
        codonalign.default_codon_table.forward_table["GCK"] = "A"
        codonalign.default_codon_table.forward_table["GTR"] = "V"
        codonalign.default_codon_table.forward_table["GTS"] = "V"
        codonalign.default_codon_table.forward_table["ATW"] = "I"
        codonalign.default_codon_table.forward_table["CTY"] = "C"
        codonalign.default_codon_table.forward_table["MGA"] = "R"
        codonalign.default_codon_table.forward_table["CAR"] = "Q"
        codonalign.default_codon_table.forward_table["ARC"] = "X"
        codonalign.default_codon_table.forward_table["CGW"] = "R"
        codonalign.default_codon_table.forward_table["GCM"] = "A"
        codonalign.default_codon_table.forward_table["CCS"] = "P"
        codonalign.default_codon_table.forward_table["CCR"] = "P"
        codonalign.default_codon_table.forward_table["TTR"] = "L"
        codonalign.default_codon_table.forward_table["TTY"] = "F"
        codonalign.default_codon_table.forward_table["AGK"] = "X"
        codonalign.default_codon_table.forward_table["GKG"] = "X"
        codonalign.default_codon_table.forward_table["GYA"] = "X"
        codonalign.default_codon_table.forward_table["ATM"] = "I"
        codonalign.default_codon_table.forward_table["AGR"] = "R"
        codonalign.default_codon_table.forward_table["AAY"] = "N"
        codonalign.default_codon_table.forward_table["AAK"] = "X"
        codonalign.default_codon_table.forward_table["GCS"] = "A"
        codonalign.default_codon_table.forward_table["KCT"] = "X"
        codonalign.default_codon_table.forward_table["TTY"] = "F"
        codonalign.default_codon_table.forward_table["RTG"] = "X"
        codonalign.default_codon_table.forward_table["GKT"] = "X"
        codonalign.default_codon_table.forward_table["ARA"] = "X"
        codonalign.default_codon_table.forward_table["CAK"] = "X"
        codonalign.default_codon_table.forward_table["MCA"] = "X"
        codonalign.default_codon_table.forward_table["MGT"] = "X"
        codonalign.default_codon_table.forward_table["GTS"] = "V"
        codonalign.default_codon_table.forward_table["CMC"] = "X"
        codonalign.default_codon_table.forward_table["TGY"] = "C"
        codonalign.default_codon_table.forward_table["CGM"] = "R"
        codonalign.default_codon_table.forward_table["GTR"] = "V"
        codonalign.default_codon_table.forward_table["TYC"] = "X"
        codonalign.default_codon_table.forward_table["CTY"] = "L"
        codonalign.default_codon_table.forward_table["GGW"] = "G"
        codonalign.default_codon_table.forward_table["KCC"] = "X"
        codonalign.default_codon_table.forward_table["TYT"] = "X"
        codonalign.default_codon_table.forward_table["GTW"] = "V"
        codonalign.default_codon_table.forward_table["WCT"] = "X"
        codonalign.default_codon_table.forward_table["GGS"] = "G"
        codonalign.default_codon_table.forward_table["CAS"] = "X"
        codonalign.default_codon_table.forward_table["GYG"] = "X"
        codonalign.default_codon_table.forward_table["GCW"] = "A"
        codonalign.default_codon_table.forward_table["MCT"] = "X"
        codonalign.default_codon_table.forward_table["GMG"] = "X"
        codonalign.default_codon_table.forward_table["ASA"] = "X"
        codonalign.default_codon_table.forward_table["GCB"] = "A"
        codonalign.default_codon_table.forward_table["WCA"] = "X"
        codonalign.default_codon_table.forward_table["AYT"] = "X"
        codonalign.default_codon_table.forward_table["CGH"] = "R"
        codonalign.default_codon_table.forward_table["RTC"] = "X"
        codonalign.default_codon_table.forward_table["MAG"] = "X"
        codonalign.default_codon_table.forward_table["YCG"] = "X"
        codonalign.default_codon_table.forward_table["RGG"] = "X"
        codonalign.default_codon_table.forward_table["MAT"] = "X"
        codonalign.default_codon_table.forward_table["GSA"] = "X"
        codonalign.default_codon_table.forward_table["AKG"] = "X"
        codonalign.default_codon_table.forward_table["CSA"] = "X"
        codonalign.default_codon_table.forward_table["MAA"] = "X"
        codonalign.default_codon_table.forward_table["CYG"] = "X"
        codonalign.default_codon_table.forward_table["CKA"] = "X"
        codonalign.default_codon_table.forward_table["CRG"] = "X"
        codonalign.default_codon_table.forward_table["YTT"] = "X"
        codonalign.default_codon_table.forward_table["ARG"] = "X"
        codonalign.default_codon_table.forward_table["RGA"] = "X"
        codonalign.default_codon_table.forward_table["KTA"] = "X"
        codonalign.default_codon_table.forward_table["CGK"] = "R"
        codonalign.default_codon_table.forward_table["MGA"] = "R"
        codonalign.default_codon_table.forward_table["TYA"] = "X"
        codonalign.default_codon_table.forward_table["ACH"] = "T"
        codonalign.default_codon_table.forward_table["RAG"] = "X"
        codonalign.default_codon_table.forward_table["CYA"] = "X"
        codonalign.default_codon_table.forward_table["GMT"] = "X"
        codonalign.default_codon_table.forward_table["GYK"] = "X"
        codonalign.default_codon_table.forward_table["YGC"] = "X"
        codonalign.default_codon_table.forward_table["AST"] = "X"
        codonalign.default_codon_table.forward_table["KTT"] = "X"
        codonalign.default_codon_table.forward_table["YAT"] = "X"
        codonalign.default_codon_table.forward_table["STA"] = "X"
        codonalign.default_codon_table.forward_table["GWT"] = "X"
        codonalign.default_codon_table.forward_table["CKG"] = "X"
        codonalign.default_codon_table.forward_table["CSG"] = "X"
        codonalign.default_codon_table.forward_table["TRT"] = "X"
        codonalign.default_codon_table.forward_table["AMT"] = "X"
        codonalign.default_codon_table.forward_table["RRM"] = "X"
        codonalign.default_codon_table.forward_table["RRA"] = "X"
        codonalign.default_codon_table.forward_table["MTS"] = "X"
        codonalign.default_codon_table.forward_table["CMT"] = "X"
        codonalign.default_codon_table.forward_table["YYT"] = "X"
        codonalign.default_codon_table.forward_table["YCA"] = "X"
        codonalign.default_codon_table.forward_table["ACB"] = "T"
        codonalign.default_codon_table.forward_table["MGR"] = "R"
        codonalign.default_codon_table.forward_table["AKT"] = "X"
        codonalign.default_codon_table.forward_table["AWT"] = "X"
        codonalign.default_codon_table.forward_table["RWA"] = "X"
        codonalign.default_codon_table.forward_table["CKT"] = "X"
        codonalign.default_codon_table.forward_table["TTM"] = "X"
        codonalign.default_codon_table.forward_table["YGG"] = "X"
        codonalign.default_codon_table.forward_table["KTG"] = "X"
        codonalign.default_codon_table.forward_table["AGM"] = "X"
        codonalign.default_codon_table.forward_table["CRA"] = "X"
        codonalign.default_codon_table.forward_table["TTW"] = "X"
        codonalign.default_codon_table.forward_table["STA"] = "X"
        codonalign.default_codon_table.forward_table["RTG"] = "X"
        codonalign.default_codon_table.forward_table["CMA"] = "X"
        codonalign.default_codon_table.forward_table["WAT"] = "X"
        codonalign.default_codon_table.forward_table["TWC"] = "X"
        codonalign.default_codon_table.forward_table["CGK"] = "R"
        codonalign.default_codon_table.forward_table["AMA"] = "X"
        codonalign.default_codon_table.forward_table["RTA"] = "X"
        codonalign.default_codon_table.forward_table["TRC"] = "X"
        codonalign.default_codon_table.forward_table["GWA"] = "X"
        codonalign.default_codon_table.forward_table["SGA"] = "X"
        codonalign.default_codon_table.forward_table["TYG"] = "X"
        codonalign.default_codon_table.forward_table["CWA"] = "X"
        codonalign.default_codon_table.forward_table["MCG"] = "X"
        codonalign.default_codon_table.forward_table["TKT"] = "X"
        codonalign.default_codon_table.forward_table["GSC"] = "X"
        codonalign.default_codon_table.forward_table["AWA"] = "X"
        codonalign.default_codon_table.forward_table["TGK"] = "X"
        codonalign.default_codon_table.forward_table["YCT"] = "X"
        codonalign.default_codon_table.forward_table["SGT"] = "X"
        codonalign.default_codon_table.forward_table["TCW"] = "S"
        codonalign.default_codon_table.forward_table["GRA"] = "X"
        codonalign.default_codon_table.forward_table["CMG"] = "X"
        codonalign.default_codon_table.forward_table["ARM"] = "X"
        codonalign.default_codon_table.forward_table["ACD"] = "T"
        codonalign.default_codon_table.forward_table["RRG"] = "X"
        codonalign.default_codon_table.forward_table["GAW"] = "X"
        codonalign.default_codon_table.forward_table["KGT"] = "X"
        codonalign.default_codon_table.forward_table["STT"] = "X"
        codonalign.default_codon_table.forward_table["ATN"] = "X"
        codonalign.default_codon_table.forward_table["MAC"] = "X"
        codonalign.default_codon_table.forward_table["SAG"] = "X"
        codonalign.default_codon_table.forward_table["ATK"] = "X"
        codonalign.default_codon_table.forward_table["KCA"] = "X"
        codonalign.default_codon_table.forward_table["CCH"] = "P"
        codonalign.default_codon_table.forward_table["SAA"] = "X"
        codonalign.default_codon_table.forward_table["AMG"] = "X"
        codonalign.default_codon_table.forward_table["ATR"] = "X"
        codonalign.default_codon_table.forward_table["RGT"] = "X"
        codonalign.default_codon_table.forward_table["GST"] = "X"
        codonalign.default_codon_table.forward_table["AGS"] = "X"
        codonalign.default_codon_table.forward_table["GKK"] = "X"
        codonalign.default_codon_table.forward_table["ATK"] = "X"
        codonalign.default_codon_table.forward_table["MTC"] = "X"
        codonalign.default_codon_table.forward_table["RMR"] = "X"
        codonalign.default_codon_table.forward_table["MTT"] = "X"
        codonalign.default_codon_table.forward_table["TWT"] = "X"
        codonalign.default_codon_table.forward_table["GRY"] = "X"
        codonalign.default_codon_table.forward_table["TKK"] = "X"
        codonalign.default_codon_table.forward_table["RCY"] = "X"
        codonalign.default_codon_table.forward_table["GWC"] = "X"
        codonalign.default_codon_table.forward_table["WCR"] = "X"
        codonalign.default_codon_table.forward_table["GTH"] = "V"
        codonalign.default_codon_table.forward_table["SCA"] = "X"
        codonalign.default_codon_table.forward_table["ATB"] = "X"
        codonalign.default_codon_table.forward_table["SWT"] = "X"
        codonalign.default_codon_table.forward_table["YGA"] = "X"
        codonalign.default_codon_table.forward_table["TTS"] = "X"
        codonalign.default_codon_table.forward_table["ARS"] = "X"
        codonalign.default_codon_table.forward_table["AKA"] = "X"
        codonalign.default_codon_table.forward_table["MTA"] = "X"
        codonalign.default_codon_table.forward_table["MTG"] = "X"
        codonalign.default_codon_table.forward_table["SYC"] = "X"
        codonalign.default_codon_table.forward_table["RRC"] = "X"
        codonalign.default_codon_table.forward_table["KAG"] = "X"
        codonalign.default_codon_table.forward_table["MKG"] = "X"
        codonalign.default_codon_table.forward_table["AGW"] = "X"
        codonalign.default_codon_table.forward_table["TSC"] = "X"
        codonalign.default_codon_table.forward_table["ART"] = "X"
        codonalign.default_codon_table.forward_table["STG"] = "X"
        codonalign.default_codon_table.forward_table["CYT"] = "X"
        codonalign.default_codon_table.forward_table["WTG"] = "X"
        codonalign.default_codon_table.forward_table["WYC"] = "X"
        codonalign.default_codon_table.forward_table["RTS"] = "X"
        codonalign.default_codon_table.forward_table["TMT"] = "X"
        codonalign.default_codon_table.forward_table["KTY"] = "X"
        codonalign.default_codon_table.forward_table["KTC"] = "X"
        codonalign.default_codon_table.forward_table["WTT"] = "X"
        codonalign.default_codon_table.forward_table["AGY"] = "S"
        codonalign.default_codon_table.forward_table["GSG"] = "X"
        codonalign.default_codon_table.forward_table["GAS"] = "X"
        codonalign.default_codon_table.forward_table["AAM"] = "X"
        codonalign.default_codon_table.forward_table["YKG"] = "X"
        codonalign.default_codon_table.forward_table["CTS"] = "L"
        codonalign.default_codon_table.forward_table["AGY"] = "S"
        codonalign.default_codon_table.forward_table["GWW"] = "X"
        codonalign.default_codon_table.forward_table["GMR"] = "X"
        codonalign.default_codon_table.forward_table["GRC"] = "X"
        codonalign.default_codon_table.forward_table["CCW"] = "X"
        codonalign.default_codon_table.forward_table["SAC"] = "X"
        codonalign.default_codon_table.forward_table["GKA"] = "X"
        codonalign.default_codon_table.forward_table["STC"] = "X"
        codonalign.default_codon_table.forward_table["AYR"] = "X"
        codonalign.default_codon_table.forward_table["WTC"] = "X"
        codonalign.default_codon_table.forward_table["RGM"] = "X"
        codonalign.default_codon_table.forward_table["KGC"] = "X"
        codonalign.default_codon_table.forward_table["WTA"] = "X"
        codonalign.default_codon_table.forward_table["MMS"] = "X"
        codonalign.default_codon_table.forward_table["AYR"] = "X"
        codonalign.default_codon_table.forward_table["GRS"] = "X"
        codonalign.default_codon_table.forward_table["RCR"] = "X"
        codonalign.default_codon_table.forward_table["GKC"] = "X"
        codonalign.default_codon_table.forward_table["MGY"] = "X"
        codonalign.default_codon_table.forward_table["KGA"] = "X"
        codonalign.default_codon_table.forward_table["YYC"] = "X"
        codonalign.default_codon_table.forward_table["GCD"] = "A"
        codonalign.default_codon_table.forward_table["GYY"] = "X"
        codonalign.default_codon_table.forward_table["DCC"] = "X"
        codonalign.default_codon_table.forward_table["GTB"] = "V"
        codonalign.default_codon_table.forward_table["TMA"] = "X"
        codonalign.default_codon_table.forward_table["WCS"] = "X"
        codonalign.default_codon_table.forward_table["MAR"] = "X"
        codonalign.default_codon_table.forward_table["GRR"] = "X"
        codonalign.default_codon_table.forward_table["KYC"] = "X"
        codonalign.default_codon_table.forward_table["AWG"] = "X"
        codonalign.default_codon_table.forward_table["CST"] = "X"
        codonalign.default_codon_table.forward_table["DCC"] = "X"
        codonalign.default_codon_table.forward_table["TGS"] = "X"
        codonalign.default_codon_table.forward_table["GCD"] = "A"
        codonalign.default_codon_table.forward_table["GYY"] = "X"
        codonalign.default_codon_table.forward_table["TYK"] = "X"
        codonalign.default_codon_table.forward_table["TMA"] = "X"
        codonalign.default_codon_table.forward_table["GRR"] = "X"
        codonalign.default_codon_table.forward_table["GTB"] = "V"
        codonalign.default_codon_table.forward_table["WCS"] = "X"
        codonalign.default_codon_table.forward_table["SRM"] = "X"
        codonalign.default_codon_table.forward_table["ARY"] = "X"
        codonalign.default_codon_table.forward_table["CWG"] = "X"
        codonalign.default_codon_table.forward_table["SAT"] = "X"
        codonalign.default_codon_table.forward_table["AYY"] = "X"
        codonalign.default_codon_table.forward_table["GYW"] = "X"
        codonalign.default_codon_table.forward_table["RWG"] = "X"
        codonalign.default_codon_table.forward_table["YTY"] = "X"
        codonalign.default_codon_table.forward_table["RSM"] = "X"
        codonalign.default_codon_table.forward_table["TST"] = "X"
        codonalign.default_codon_table.forward_table["CYK"] = "X"
        codonalign.default_codon_table.forward_table["SMS"] = "X"
        codonalign.default_codon_table.forward_table["MRA"] = "X"
        codonalign.default_codon_table.forward_table["CRW"] = "X"
        codonalign.default_codon_table.forward_table["GBC"] = "X"
        codonalign.default_codon_table.forward_table["RAR"] = "X"
        codonalign.default_codon_table.forward_table["ARR"] = "X"
        codonalign.default_codon_table.forward_table["GRW"] = "X"
        codonalign.default_codon_table.forward_table["RAY"] = "B"
        codonalign.default_codon_table.forward_table["SAW"] = "X"
        codonalign.default_codon_table.forward_table["AMR"] = "X"
        codonalign.default_codon_table.forward_table["GWS"] = "X"
        codonalign.default_codon_table.forward_table["YKT"] = "X"
        codonalign.default_codon_table.forward_table["GWK"] = "X"
        codonalign.default_codon_table.forward_table["KMT"] = "X"
        codonalign.default_codon_table.forward_table["YCK"] = "X"
        codonalign.default_codon_table.forward_table["MGS"] = "X"
        codonalign.default_codon_table.forward_table["SSS"] = "X"
        codonalign.default_codon_table.forward_table["AWK"] = "X"

        
        

        align = codonalign.build(aa_aln, na_seq, max_score=20)

        for record in range(0, len(align)):
            align._records[record].description = ""  # removes description by looping through the records

        SeqIO.write(align, output.alignment, "fasta")

rule hyphy:
    input:
        tree = "families/family_{fam}.tree",
        align = "families/family_{fam}.aln.codon"
    output:
        json = "families/family_{fam}.aln.codon.FUBAR.json",
        log = "families/family_{fam}.aln.codon.FUBAR.log"
    conda:
        "envs/hyphy.yaml"
    shell:
        "tmpThing=$(find " + wd +
        "/.. -name FUBAR.bf|tail -n 1);(echo 1;echo " +
        wd + "/{input.align}; echo " + wd +
        "/{input.tree}; echo 20;echo 5;echo 3;echo 0.5 )|hyphy $tmpThing > {output.log} || touch {output.log} {output.json} "

rule finalStatistics:
    input:
        json = dynamic("families/family_{fam}.aln.codon.FUBAR.json"),
        log = dynamic("families/family_{fam}.aln.codon.FUBAR.log")
    output:
        "final_results/famsUnderSelection.txt"
    run:
        with open(output[0], "w") as out:
            out.write("family numSitesUnderSelection\n")
            for currentFile in input.log:
                with open(currentFile) as f:
                    for line in f:
                        if "## FUBAR" in line:
                            if "no" not in line:
                                result = re.search('inferred(.*)sites', line)
                                out.write(currentFile.split(
                                    "/")[-1].split(".")[0] + " " + result.group(1) + "\n")
